// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUYLmeTquNk37Z2pzrRWQ0P2BU97CG8nE',
    appId: '1:924991360692:web:459effa7e7d961fc8451e1',
    messagingSenderId: '924991360692',
    projectId: 'myfirebasenotify-d7e8f',
    authDomain: 'myfirebasenotify-d7e8f.firebaseapp.com',
    storageBucket: 'myfirebasenotify-d7e8f.firebasestorage.app',
    measurementId: 'G-C576F8BM9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApz6yQNNQJxCe5VPTe58Svm_HRK15M4E',
    appId: '1:924991360692:android:9f5521e268342b158451e1',
    messagingSenderId: '924991360692',
    projectId: 'myfirebasenotify-d7e8f',
    storageBucket: 'myfirebasenotify-d7e8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlQa6ypDDyotzDMpqfBEzv-VwjgEUYVfo',
    appId: '1:924991360692:ios:11f7612516453a958451e1',
    messagingSenderId: '924991360692',
    projectId: 'myfirebasenotify-d7e8f',
    storageBucket: 'myfirebasenotify-d7e8f.firebasestorage.app',
    iosBundleId: 'com.example.getxprofirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlQa6ypDDyotzDMpqfBEzv-VwjgEUYVfo',
    appId: '1:924991360692:ios:11f7612516453a958451e1',
    messagingSenderId: '924991360692',
    projectId: 'myfirebasenotify-d7e8f',
    storageBucket: 'myfirebasenotify-d7e8f.firebasestorage.app',
    iosBundleId: 'com.example.getxprofirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBURlZkll3lxl0hBNmjCTNeTfJIs3Scz-w',
    appId: '1:924991360692:web:249486fd08658ea18451e1',
    messagingSenderId: '924991360692',
    projectId: 'myfirebasenotify-d7e8f',
    authDomain: 'myfirebasenotify-d7e8f.firebaseapp.com',
    storageBucket: 'myfirebasenotify-d7e8f.firebasestorage.app',
    measurementId: 'G-T1QP7F3NR3',
  );

}